# Generated by Django 3.1.7 on 2021-02-27 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'verbose_name': '강의', 'verbose_name_plural': '강의'},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name': '트레이너', 'verbose_name_plural': '트레이너'},
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='trainer',
            name='address',
            field=models.CharField(blank=True, max_length=20, verbose_name='지역'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='place',
            field=models.CharField(blank=True, max_length=20, verbose_name='장소'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='genre',
            field=models.ManyToManyField(blank=True, to='trainer.Genre', verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='name',
            field=models.CharField(max_length=20, verbose_name='강의명'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='summary',
            field=models.TextField(max_length=1000, verbose_name='강의 설명'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainer.trainer'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='genre',
            field=models.ManyToManyField(blank=True, to='trainer.Genre', verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='hashtag',
            field=models.ManyToManyField(blank=True, to='trainer.Hashtag'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(max_length=10, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='summary',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterModelTable(
            name='lecture',
            table='강의',
        ),
        migrations.AlterModelTable(
            name='trainer',
            table='트레이너',
        ),
        migrations.DeleteModel(
            name='Gym',
        ),
    ]
