# Generated by Django 3.1.7 on 2021-02-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_auto_20210227_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='genretext',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='TrainerInformation',
        ),
    ]
