# Generated by Django 3.1.7 on 2021-02-28 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import trainer.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainer', '0005_auto_20210227_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='filename',
            field=models.CharField(max_length=64, null=True, verbose_name='첨부파일명'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='upload_files',
            field=models.FileField(blank=True, null=True, upload_to=trainer.models.get_file_path, verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='address',
            field=models.CharField(max_length=40, null=True, verbose_name='지역'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='trainer.Genre', verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='genretext',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='hashtag',
            field=models.ManyToManyField(blank=True, null=True, to='trainer.Hashtag'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='place',
            field=models.CharField(max_length=40, null=True, verbose_name='장소'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='tagtext',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
    ]
