# Generated by Django 3.1.7 on 2021-02-28 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0007_auto_20210228_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='upload_files',
        ),
    ]
