# Generated by Django 3.1.7 on 2021-02-28 20:04

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0008_auto_20210228_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
