# Generated by Django 3.1.7 on 2021-02-28 22:50

from django.db import migrations, models
import imagekit.models.fields
import trainer.models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0009_trainer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='imagename',
            field=models.CharField(max_length=64, null=True, verbose_name='이미지파일'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=trainer.models.get_profile_image_path, verbose_name='프로필 이미지'),
        ),
    ]
