# Generated by Django 3.1.7 on 2021-03-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0010_auto_20210228_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='genre',
        ),
    ]
