# Generated by Django 3.1.7 on 2021-03-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0013_auto_20210305_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='sns1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='sns2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='sns3',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='sns4',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='sns5',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
