# Generated by Django 3.1.7 on 2021-03-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='trainer_idd',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='genretext',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
