# Generated by Django 3.1.7 on 2021-03-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20210301_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='trainer_idd',
        ),
    ]
